#!/bin/bash
wget https://github.com/summaxx/myscript/raw/refs/heads/master/xg.sh && chmod +x xg.sh
wget https://github.com/summaxx/myscript/raw/refs/heads/master/gcpnezhe.sh && chmod +x gcpnezhe.sh
env NZ_SERVER=nz.tim.cx:8008 NZ_TLS=false NZ_CLIENT_SECRET=Fb35iO5oxQK2GhcMjlxTwUXiqAql4th4 ./gcpnezhe.sh
cp /etc/systemd/system/nezha-agent.service .
cat <<END >> tt.sh
#!/bin/bash
sleep 5
gnome-terminal  # Replace with your terminal command
exit 0
END
chmod +x tt.sh
chod +x nz.sh
echo "sudo /home/user/nz.sh" | sudo tee -a .bashrc
echo "sudo /home/user/xg.sh" | sudo tee -a .bashrc
